name: CI

# Only run on code_cleanup for now, since it is the most experimental branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: wpilib/roborio-cross-ubuntu:2022-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    - name: Format code using Spotless
      run: ./gradlew spotlessCheck

    - name: Compile and run tests on robot code
      run: ./gradlew build
